[main.padding]
    x = 4
    y = 4
    [main.padding.mobile]
        x = 2

[zerotest.padding]
    x = 4
    y = 4
    [zerotest.padding.mobile]
        x = 0

[fallbacktest.padding]
    x = 3
    y = 3
